# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-12 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0011_auto_20171227_1431'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommRequest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('email', models.TextField(max_length=1000)),
                ('topics', models.TextField(max_length=1000)),
                ('source', models.CharField(blank=True, max_length=100, null=True)),
                ('doc_recomm', models.CharField(blank=True, max_length=100, null=True)),
                ('class_model', models.FloatField(blank=True, null=True)),
                ('page', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created',),
            },
        ),
    ]
