# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-12 00:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0012_recommrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommrequest',
            name='time_request',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
