# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2019-09-12 01:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search_engine', '0013_recommrequest_time_request'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommrequest',
            name='class_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
